"use client";

import Image from "next/image";
import bharat1 from "@/assets/logos/bharat1.png";
import sentrix from "@/assets/logos/sentrix.png";

// Assets are generated by scripts/trim-logos.mjs, which crops the transparent
// padding off the source files in logos/. That matters: the supplied marks pad
// their canvases very differently (Bharat's ink filled 71% of its canvas
// height, Sentrix's only 37%), so sizing by canvas height rendered Sentrix at
// about half the optical size. Trimmed, a single height prop gives both marks
// matching visual weight.
//
// Ratios come from the static imports' intrinsic dimensions rather than being
// hardcoded, so swapping a logo file cannot silently stretch it -- rerun
// trim-logos.mjs and the layout adapts.
//
// Contrast measured by scripts/png-colors.mjs:
//                   on #0f0f17    on #ffffff
//   Bharat-1.ai       2.56:1        7.38:1
//   Sentrix           3.01:1        ~6.1:1
// Hence the white plate.

export type PlateStyle = "white" | "translucent" | "none";

const PLATE_BG: Record<PlateStyle, string | undefined> = {
  white: "var(--p-white)",
  translucent: "rgba(255,255,255,0.85)",
  none: undefined,
};

export function PoweredBy({
  height = 30,
  plate = "white",
  fullWidth = true,
  className = "",
}: {
  /** Optical height of each mark in px. Widths follow each logo's true ratio. */
  height?: number;
  plate?: PlateStyle;
  /** Stretch the plate edge-to-edge instead of hugging the logos. */
  fullWidth?: boolean;
  className?: string;
}) {
  const bw = Math.round(height * (bharat1.width / bharat1.height));
  const sw = Math.round(height * (sentrix.width / sentrix.height));
  const padY = Math.max(6, Math.round(height * 0.34));
  const bg = PLATE_BG[plate];
  const plated = plate !== "none";

  return (
    <div
      className={`relative z-[60] flex items-center justify-center ${
        fullWidth ? "w-full" : ""
      } ${className}`}
      style={{
        background: bg,
        paddingTop: plated ? padY : undefined,
        paddingBottom: plated ? padY : undefined,
        paddingLeft: 16,
        paddingRight: 16,
        // Hard rule instead of a full pixel-panel box: a full-bleed bar reads
        // better with a single bottom edge than with a border on all four sides.
        borderBottom: plated ? "3px solid var(--p-black)" : undefined,
      }}
    >
      <div
        className="flex items-center"
        style={{ gap: Math.round(height * 0.75) }}
      >
        <Image
          src={bharat1}
          alt="Bharat-1.ai"
          width={bw}
          height={height}
          priority
          style={{ width: bw, height, objectFit: "contain" }}
        />
        <div
          aria-hidden
          style={{
            width: 2,
            height: Math.round(height * 1.1),
            background: plated ? "var(--p-silver)" : "var(--p-slate)",
          }}
        />
        <Image
          src={sentrix}
          alt="Sentrix"
          width={sw}
          height={height}
          priority
          style={{ width: sw, height, objectFit: "contain" }}
        />
      </div>
    </div>
  );
}
