// 16x16 fixed-colour item sprites, drawn in the chunky "Minecraft item" idiom:
// hard dark outline, flat fills, 2-3 shades, strong silhouette, no thin details.
//
// Unlike the tinted sprites in sprites.ts these use an explicit colour alphabet,
// because a pill must read as a pill and a leaf as a leaf regardless of which
// sector's accent colour happens to be active.
//
// Colour alphabet:
//   .  transparent   k  outline      j  shadow   z  slate    Z  silver
//   w  off-white     W  white
//   r  dark red      R  red          e  coral    p  pink
//   n  rust          o  orange       a  amber    d  sand
//   b  bronze        y  gold         Y  yellow
//   f  forest        g  green        l  lime     L  mint
//   t  deep teal     T  teal         c  cyan     i  ice
//   v  navy          B  blue         S  sky
//   u  purple        U  violet

import { PaletteIndex } from "./palette";
import { SectorId } from "@/game/types";

export const ITEM_SIZE = 16;

const FIXED: Record<string, PaletteIndex> = {
  k: 0, j: 2, z: 3, Z: 5, w: 6, W: 7,
  r: 8, R: 9, e: 10, p: 11,
  n: 12, o: 13, a: 14, d: 15,
  b: 16, y: 17, Y: 18,
  f: 19, g: 20, l: 21, L: 22,
  t: 23, T: 24, c: 25, i: 26,
  v: 27, B: 28, S: 29,
  u: 30, U: 31,
};

export function resolveFixed(ch: string): PaletteIndex | null {
  if (ch === ".") return null;
  const v = FIXED[ch];
  return v === undefined ? null : v;
}

export type ItemSprite = readonly string[];

// ======================================================== COLLECTIBLES ======

const CLIPBOARD: ItemSprite = [
  "................",
  "......kkkk......",
  "..kkkkZZZZkkkk..",
  "..knnkZZZZknnk..",
  "..knwwwwwwwwnk..",
  "..knwkkkkkkwnk..",
  "..knwwwwwwwwnk..",
  "..knwkkkkkkwnk..",
  "..knwwwwwwwwnk..",
  "..knwkkkkwwwnk..",
  "..knwwwwwwwwnk..",
  "..knnnnnnnnnnk..",
  "..kkkkkkkkkkkk..",
  "................",
  "................",
  "................",
];

const DNA: ItemSprite = [
  "................",
  "...k........k...",
  "...kc......ck...",
  "....kc....ck....",
  ".....kcccck.....",
  "......kcck......",
  ".....kc..ck.....",
  "....kc....ck....",
  "....kc....ck....",
  ".....kc..ck.....",
  "......kcck......",
  ".....kcccck.....",
  "....kc....ck....",
  "...kc......ck...",
  "...k........k...",
  "................",
];

const PILL: ItemSprite = [
  "................",
  "....kkkkkkkk....",
  "...kRRRRRRRRk...",
  "..kRReeeeeeRRk..",
  "..kRReeeeeeRRk..",
  "..kRReeeeeeRRk..",
  "..kkkkkkkkkkkk..",
  "..kwwwwwwwwwwk..",
  "..kwWWWWWWWWwk..",
  "..kwWWWWWWWWwk..",
  "...kwWWWWWWwk...",
  "....kkkkkkkk....",
  "................",
  "................",
  "................",
  "................",
];

const BARCHART: ItemSprite = [
  "................",
  "..kkkkkkkkkkkk..",
  "..kjjjjjjjjjjk..",
  "..kjjjjjjkllk...",
  "..kjjjjjjklLk...",
  "..kjjkccklLLk...",
  "..kjjkcckLLLk...",
  "..kYYkcckLLLk...",
  "..kYYkcckLLLk...",
  "..kYYkcckLLLk...",
  "..kkkkkkkkkkk...",
  "..kjjjjjjjjjjk..",
  "..kkkkkkkkkkkk..",
  "................",
  "................",
  "................",
];

const MEDAL: ItemSprite = [
  "................",
  "....kk....kk....",
  "....kRk..kBk....",
  "....kRk..kBk....",
  "....kRkkkkBk....",
  ".....kkyykk.....",
  "....kyYYYYyk....",
  "...kyYYWWYYyk...",
  "...kyYWWWWYyk...",
  "...kyYYWWYYyk...",
  "....kyYYYYyk....",
  ".....kkyykk.....",
  "......kkkk......",
  "................",
  "................",
  "................",
];

const HEART: ItemSprite = [
  "................",
  "..kkkk....kkkk..",
  ".kReeRk..kReeRk.",
  "kReeeeRkkReeeeRk",
  "kReeeeeeeeeeeeRk",
  "kReeeeeeeeeeeeRk",
  "kRReeeeeeeeeeRRk",
  ".kRReeeeeeeeRRk.",
  "..kRReeeeeeRRk..",
  "...kRReeeeRRk...",
  "....kRReeRRk....",
  ".....kRRRRk.....",
  "......kRRk......",
  ".......kk.......",
  "................",
  "................",
];

const PUZZLE: ItemSprite = [
  "................",
  "..kkkkkkkk......",
  "..kUUUUUUk......",
  "..kUUUUUUkkkk...",
  "..kUUUUUUUUUk...",
  "..kUUUUUUUUUk...",
  "..kUUUUUUkkkk...",
  "..kUUUUUUk......",
  "..kkkkUUUk......",
  "....kUUUUkkkkk..",
  "....kUUUUUUUUk..",
  "....kUUUUUUUUk..",
  "....kUUUUUUUUk..",
  "....kkkkkkkkkk..",
  "................",
  "................",
];

const GEAR: ItemSprite = [
  "................",
  "....kk....kk....",
  "....kZk..kZk....",
  "..kkkZkkkkZkkk..",
  "..kZZZZZZZZZZk..",
  "..kZZZkkkkZZZk..",
  "kkkZZkjjjjkZZkkk",
  "kZZZZkjjjjkZZZZk",
  "kZZZZkjjjjkZZZZk",
  "kkkZZkjjjjkZZkkk",
  "..kZZZkkkkZZZk..",
  "..kZZZZZZZZZZk..",
  "..kkkZkkkkZkkk..",
  "....kZk..kZk....",
  "....kk....kk....",
  "................",
];

const BATTERY: ItemSprite = [
  "................",
  ".....kkkkkk.....",
  "....kkZZZZkk....",
  "...kkkkkkkkkk...",
  "...kZllllllZk...",
  "...kZllllllZk...",
  "...kZllllllZk...",
  "...kZllllllZk...",
  "...kZllllllZk...",
  "...kZllllllZk...",
  "...kZlYYYYlZk...",
  "...kZlYYYYlZk...",
  "...kZllllllZk...",
  "...kkkkkkkkkk...",
  "................",
  "................",
];

const ORB: ItemSprite = [
  "................",
  ".....kkkkkk.....",
  "...kkUUUUUUkk...",
  "..kUUiiUUUUUUk..",
  ".kUUiiUUUUUUUUk.",
  ".kUiiUUUUUUUUUk.",
  "kUUUUUUUUUUUUUk.",
  "kUUUUUUUUUUUUUUk",
  "kUUUUUUUUUUUUUUk",
  "kUUUUUUUUUUUUUUk",
  ".kUUUUUUUUUUUUk.",
  ".kUUUUUUUUUUUUk.",
  "..kUUUUUUUUUUk..",
  "...kkUUUUUUkk...",
  ".....kkkkkk.....",
  "................",
];

const BRAIN: ItemSprite = [
  "................",
  "....kkkkkkkk....",
  "..kkpppppppkk...",
  ".kpppkppkpppppk.",
  "kppkpppppkppppk.",
  "kppppkppppkpppk.",
  "kpkppppkppppkpk.",
  "kppppkppppkpppk.",
  "kppkppppkppppppk",
  "kppppkppppkpppk.",
  ".kppppkppppkpk..",
  ".kpppppppppppk..",
  "..kkppppppppk...",
  "....kkkkkkkk....",
  "................",
  "................",
];

const DISH: ItemSprite = [
  "................",
  "..........kk....",
  ".........kck....",
  "..kkkk..kck.....",
  ".kiiiikkck......",
  "kiiiiiick.......",
  "kiiiiiik........",
  "kiiiiiik........",
  ".kiiiiik........",
  "..kkkkk.........",
  "....kzk.........",
  "....kzk.........",
  "..kkkzkkk.......",
  "..kzzzzzk.......",
  "..kkkkkkk.......",
  "................",
];

const PALETTE_ART: ItemSprite = [
  "................",
  "....kkkkkkk.....",
  "..kknnnnnnnkk...",
  ".knRRnnnnnnnnk..",
  "knnRRnnkkknnnnk.",
  "knnnnnkYYYknnnk.",
  "knBBnnkYYYknnnk.",
  "knBBnnnkkknnnnk.",
  "knnnnnnnnnnnnk..",
  ".knnggnnnnnnk...",
  ".knnggnnnnnk....",
  "..knnnnnnkk.....",
  "...kkkkkk.......",
  "................",
  "................",
  "................",
];

const NOTE: ItemSprite = [
  "................",
  "..........kkkk..",
  "..........kUUUk.",
  "..........kUUUk.",
  "........kkkUUUk.",
  "........kUUUUUk.",
  "........kUUkkkk.",
  "........kUUk....",
  "........kUUk....",
  "..kkkk..kUUk....",
  ".kUUUUk.kUUk....",
  "kUUUUUUkkUUk....",
  "kUUUUUUUUUUk....",
  "kUUUUUUUUUUk....",
  ".kUUUUkkUUk.....",
  "..kkkk..kk......",
];

const CAMERA: ItemSprite = [
  "................",
  "................",
  "......kkkk......",
  "...kkkjjjjkkkk..",
  "..kzzzzzzzzzzzk.",
  "..kzZZZkkkZZZzk.",
  "..kzZkkjjjkkZzk.",
  "..kzZkjSSSjkZzk.",
  "..kzZkjSSSjkZzk.",
  "..kzZkkjjjkkZzk.",
  "..kzZZZkkkZZZzk.",
  "..kzzzzzzzzzzzk.",
  "..kkkkkkkkkkkkk.",
  "................",
  "................",
  "................",
];

const WRENCH: ItemSprite = [
  "................",
  "..kkk...........",
  ".kZZZk..........",
  "kZZkZZk.........",
  "kZZkZZk.........",
  "kZZkZZk.........",
  ".kZZZk..........",
  "..kZZZk.........",
  "...kZZZk........",
  "....kZZZk.......",
  ".....kZZZk......",
  "......kZZZk.....",
  ".......kZZZk....",
  "........kZZZk...",
  ".........kZZk...",
  "..........kkk...",
];

const SENSOR: ItemSprite = [
  "................",
  "......kk........",
  "......kck.......",
  "...kkkkckkkk....",
  "..kzzzzczzzzk...",
  "..kzZZZZZZZzk...",
  "..kzZkkkkkZzk...",
  "..kzZkiiikZzk...",
  "..kzZkiiikZzk...",
  "..kzZkkkkkZzk...",
  "..kzZZZZZZZzk...",
  "..kzzzzzzzzzk...",
  "..kkkkkkkkkkk...",
  "...kk.....kk....",
  "................",
  "................",
];

const CRATE: ItemSprite = [
  "................",
  "................",
  ".kkkkkkkkkkkkkk.",
  ".knnnnnnnnnnnnk.",
  ".knbbbbbbbbbbnk.",
  ".knbddddddddbnk.",
  ".knbdkkkkkkdbnk.",
  ".knbdknnnnkdbnk.",
  ".knbdknnnnkdbnk.",
  ".knbdkkkkkkdbnk.",
  ".knbddddddddbnk.",
  ".knbbbbbbbbbbnk.",
  ".knnnnnnnnnnnnk.",
  ".kkkkkkkkkkkkkk.",
  "................",
  "................",
];

const SPROUT: ItemSprite = [
  "................",
  "................",
  "...kkk....kkk...",
  "..kglLk..kLlgk..",
  ".kgllLLk.kLLllgk",
  ".kgllLLkkkLLllgk",
  "..kgllLkfkLllgk.",
  "...kkkkkfkkkkk..",
  "........f.......",
  "........f.......",
  ".......kfk......",
  "..kkkkkkfkkkkk..",
  "..knnnnnnnnnnk..",
  "..kbbbbbbbbbbk..",
  "..kkkkkkkkkkkk..",
  "................",
];

const DROP: ItemSprite = [
  "................",
  ".......kk.......",
  ".......kk.......",
  "......kSSk......",
  "......kSSk......",
  ".....kSSSSk.....",
  "....kSSSSSSk....",
  "...kSSiiSSSSk...",
  "..kSSiiSSSSSSk..",
  "..kSSiiSSSSSSk..",
  "..kSSSSSSSSSSk..",
  "..kSSSSSSSSSSk..",
  "...kSSSSSSSSk...",
  "....kkSSSSkk....",
  "......kkkk......",
  "................",
];

const SATELLITE: ItemSprite = [
  "................",
  "................",
  "kkkk......kkkk..",
  "kBBk.kkkk.kBBk..",
  "kBBkkzzzzkkBBk..",
  "kBBkzZZZZzkBBk..",
  "kBBkzZiiZzkBBk..",
  "kkkkzZiiZzkkkk..",
  "....zZZZZz......",
  "....kzzzzk......",
  ".....kkkk.......",
  "......kk........",
  ".....kiik.......",
  "......kk........",
  "................",
  "................",
];

const MAP_ITEM: ItemSprite = [
  "................",
  "..kkkkkkkkkkkk..",
  "..kddddddddddk..",
  "..kdLLdddddddk..",
  "..kdLLLdddRddk..",
  "..kddLLddRRRdk..",
  "..kdddLdddRddk..",
  "..kddSSSddddddk.",
  "..kdSSSSSdddddk.",
  "..kddSSSdddLLdk.",
  "..kdddddddLLLdk.",
  "..kddRddddLLddk.",
  "..kdRRRdddddddk.",
  "..kddRddddddddk.",
  "..kkkkkkkkkkkkk.",
  "................",
];

const PIN: ItemSprite = [
  "................",
  ".....kkkkkk.....",
  "...kkRRRRRRkk...",
  "..kRRRRRRRRRRk..",
  "..kRRRkkkkRRRk..",
  "..kRRkWWWWkRRk..",
  "..kRRkWWWWkRRk..",
  "..kRRRkkkkRRRk..",
  "..kRRRRRRRRRRk..",
  "...kRRRRRRRRk...",
  "....kRRRRRRk....",
  ".....kRRRRk.....",
  "......kRRk......",
  ".......kk.......",
  "................",
  "................",
];

const BOOKS: ItemSprite = [
  "................",
  "................",
  "...kkkkkkkkkk...",
  "...kBBBBBBBBk...",
  "...kBWWWWWWBk...",
  "...kkkkkkkkkk...",
  "..kkkkkkkkkkkk..",
  "..kRRRRRRRRRRk..",
  "..kRWWWWWWWWRk..",
  "..kkkkkkkkkkkk..",
  ".kkkkkkkkkkkkkk.",
  ".kggggggggggggk.",
  ".kgWWWWWWWWWWgk.",
  ".kkkkkkkkkkkkkk.",
  "................",
  "................",
];

const PENCIL: ItemSprite = [
  "................",
  "..........kkk...",
  ".........kppk...",
  "........kppkk...",
  ".......kkkkk....",
  "......kYYYk.....",
  ".....kYYYk......",
  "....kYYYk.......",
  "...kYYYk........",
  "..kYYYk.........",
  ".kYYYk..........",
  "kddYk...........",
  "kddk............",
  "kjk.............",
  "kk..............",
  "................",
];

const LEAF: ItemSprite = [
  "................",
  "............kk..",
  "..........kklgk.",
  ".......kkklllgk.",
  ".....kkllllllgk.",
  "...kkllllfllgk..",
  "..klllllfllgk...",
  ".kllllllfllgk...",
  "kllllllfllgk....",
  "kllllffllgk.....",
  "kllllfllgk......",
  "kgllfllgk.......",
  ".kgfllgk........",
  "..kgggk.........",
  "...kkk..........",
  "................",
];

const SUN: ItemSprite = [
  "................",
  "......kkk.......",
  "..k...kYk...k...",
  "..kk..kYk..kk...",
  "...kk.kkk.kk....",
  "....kkYYYkk.....",
  "kkkkYYYYYYYkkkk.",
  ".kYYYYWWWYYYYk..",
  "kkkkYYYWYYYkkkk.",
  "....kkYYYkk.....",
  "...kk.kkk.kk....",
  "..kk..kYk..kk...",
  "..k...kYk...k...",
  "......kkk.......",
  "................",
  "................",
];

const WIND: ItemSprite = [
  "................",
  "................",
  "...kkkkkk.......",
  "..kiiiiiikk.....",
  ".ki......iik....",
  "kk........kik...",
  "..........kik...",
  ".kkkkkkkkkkk....",
  "kiiiiiiiiiik....",
  "kk.........kkk..",
  "...........kiik.",
  "...kkkkkkkkkiik.",
  "..kiiiiiiiiiik..",
  "...kk...........",
  "................",
  "................",
];

// ============================================================ HAZARDS ======

const VIRUS: ItemSprite = [
  "................",
  "....k..kk..k....",
  "....k..kk..k....",
  ".k..kkkkkkkk..k.",
  ".kkkRRRRRRRRkkk.",
  "..kRRRrrrrRRRk..",
  "kkkRrrRRRRrrRkkk",
  "..kRrRRWWRRrRk..",
  "..kRrRRWWRRrRk..",
  "kkkRrrRRRRrrRkkk",
  "..kRRRrrrrRRRk..",
  ".kkkRRRRRRRRkkk.",
  ".k..kkkkkkkk..k.",
  "....k..kk..k....",
  "....k..kk..k....",
  "................",
];

const BROKEN_LOCK: ItemSprite = [
  "................",
  "....kkkk........",
  "...kyyyyk.......",
  "..kyykkyyk......",
  "..kyk..kyk......",
  "..kyk..kkk......",
  "..kyk...........",
  "kkkkkkkkkkkk....",
  "kyyyyyyyyyyk....",
  "kyyykkkkyyyk....",
  "kyykjjjjkyyk....",
  "kyyykkjjkyyk....",
  "kyyyyykkyyyk....",
  "kyyyyyyyyyyk....",
  "kkkkkkkkkkkk....",
  "................",
];

const XMARK: ItemSprite = [
  "................",
  "..kkk......kkk..",
  ".kRRRk....kRRRk.",
  "kRReeRk..kReeRRk",
  "kReeeeRkkReeeeRk",
  ".kReeeeReeeeRk..",
  "..kReeeeeeeeRk..",
  "...kReeeeeeRk...",
  "...kReeeeeeRk...",
  "..kReeeeeeeeRk..",
  ".kReeeeReeeeRk..",
  "kReeeeRkkReeeeRk",
  "kRReeRk..kReeRRk",
  ".kRRRk....kRRRk.",
  "..kkk......kkk..",
  "................",
];

const BANDAGE: ItemSprite = [
  "................",
  "................",
  "..kkkk..........",
  ".kddddkk........",
  "kdWWWWddkk......",
  "kdWWWWWWddkk....",
  ".kddWWWWWWddkk..",
  "..kkddWWWWWWddk.",
  "....kkddWWWWddk.",
  "......kkddWWddk.",
  "........kkddddk.",
  "..........kkkkk.",
  "................",
  "................",
  "................",
  "................",
];

const RAINCLOUD: ItemSprite = [
  "................",
  "....kkkkk.......",
  "..kkzzzzzkk.....",
  ".kzzzzzzzzzkkk..",
  "kzzZZZZZZzzzzzk.",
  "kzZZZZZZZZZZZzk.",
  "kzzzzzzzzzzzzzk.",
  ".kkkkkkkkkkkkk..",
  "..k.k.k.k.k.k...",
  "..S.S.S.S.S.S...",
  "..S.S.S.S.S.S...",
  "...k.k.k.k.k....",
  "...S.S.S.S.S....",
  "...S.S.S.S.S....",
  "................",
  "................",
];

const DOWNCHART: ItemSprite = [
  "................",
  "..kkkkkkkkkkkk..",
  "..kjjjjjjjjjjk..",
  "..kRRkjjjjjjjk..",
  "..kRRRkjjjjjjk..",
  "..kjkRRkjjjjjk..",
  "..kjjkRRkjjjjk..",
  "..kjjjkRRkjjjk..",
  "..kjjjjkRRkjjk..",
  "..kjjjjjkRRRRk..",
  "..kjjjjjjkRRRk..",
  "..kjjjjjjjkRRk..",
  "..kkkkkkkkkkkk..",
  "................",
  "................",
  "................",
];

const EXPLOSION: ItemSprite = [
  "................",
  "...k...kk...k...",
  "...kk.kYYk.kk...",
  "....kkkYYkkk....",
  "..kkkYYYYYYkkk..",
  ".kYYYYoooYYYYk..",
  "kkYYoooRRoooYkk.",
  "..kYooRRRRooYk..",
  "..kYooRRRRooYk..",
  "kkYYoooRRoooYkk.",
  ".kYYYYoooYYYYk..",
  "..kkkYYYYYYkkk..",
  "....kkkYYkkk....",
  "...kk.kYYk.kk...",
  "...k...kk...k...",
  "................",
];

const TRUCK: ItemSprite = [
  "................",
  "................",
  "....kkkkkkkkkk..",
  "....kZZZZZZZZk..",
  "kkkkkZZZZZZZZk..",
  "kSSSkZZZZZZZZk..",
  "kSSSkZZZZZZZZk..",
  "kkkkkkkkkkkkkk..",
  "kzzzzzzzzzzzzk..",
  "kkkkkkkkkkkkkk..",
  "..kkk......kkk..",
  ".kjjjk....kjjjk.",
  ".kjWjk....kjWjk.",
  ".kjjjk....kjjjk.",
  "..kkk......kkk..",
  "................",
];

const FIRE: ItemSprite = [
  "................",
  ".......kk.......",
  "......kRRk......",
  ".....kRoRRk.....",
  "....kRooRRk.....",
  "...kRoooRRk.....",
  "...kRooaoRRk....",
  "..kRoaaaaoRRk...",
  "..kRoaYYaooRk...",
  ".kRoaYYYYaoRk...",
  ".kRoaYYYYaoRk...",
  ".kRRoaYYaooRk...",
  "..kRRooaooRRk...",
  "...kRRRoRRRk....",
  "....kkkkkkk.....",
  "................",
];

const SNOWFLAKE: ItemSprite = [
  "................",
  ".......kk.......",
  "...k..kiik..k...",
  "...kk.kiik.kk...",
  "....kkkiikkk....",
  ".....kiiiik.....",
  "kkkkkiiiiiikkkkk",
  ".kiiiiiWWiiiiik.",
  ".kiiiiiWWiiiiik.",
  "kkkkkiiiiiikkkkk",
  ".....kiiiik.....",
  "....kkkiikkk....",
  "...kk.kiik.kk...",
  "...k..kiik..k...",
  ".......kk.......",
  "................",
];

const LIGHTNING: ItemSprite = [
  "................",
  ".........kkk....",
  "........kYYk....",
  ".......kYYYk....",
  "......kYYYk.....",
  ".....kYYYk......",
  "....kYYYkkkk....",
  "...kYYYYYYYk....",
  "...kkkkYYYYk....",
  "......kYYYk.....",
  ".....kYYYk......",
  "....kYYYk.......",
  "...kYYYk........",
  "...kYYk.........",
  "...kk...........",
  "................",
];

const VOID_HOLE: ItemSprite = [
  "................",
  "....kkkkkkkk....",
  "..kkUUUUUUUUkk..",
  ".kUUUUUUUUUUUUk.",
  "kUUUkkkkkkkkUUk.",
  "kUUkjjjjjjjjkUk.",
  "kUkjjjjjjjjjjkk.",
  "kUkjjjjjjjjjjk..",
  "kUkjjjjjjjjjjk..",
  "kUkjjjjjjjjjjkk.",
  "kUUkjjjjjjjjkUk.",
  "kUUUkkkkkkkkUUk.",
  ".kUUUUUUUUUUUUk.",
  "..kkUUUUUUUUkk..",
  "....kkkkkkkk....",
  "................",
];

const WARNING: ItemSprite = [
  "................",
  ".......kk.......",
  "......kYYk......",
  "......kYYk......",
  ".....kYYYYk.....",
  ".....kYkkYk.....",
  "....kYYkkYYk....",
  "....kYYkkYYk....",
  "...kYYYkkYYYk...",
  "...kYYYkkYYYk...",
  "..kYYYYYYYYYYk..",
  "..kYYYYkkYYYYk..",
  ".kYYYYYkkYYYYYk.",
  ".kkkkkkkkkkkkkk.",
  "................",
  "................",
];

const SLEEP: ItemSprite = [
  "................",
  ".........kkkkk..",
  ".........kZZZk..",
  "........kkkZZk..",
  "..kkkk..kZZZkk..",
  ".kzzzzk.kZZk....",
  "kzzzzzzkkkkkk...",
  "kzkzzkzk........",
  "kzzzzzzk.kkkk...",
  "kzzzzzzk.kZZk...",
  "kzkkkkzk.kkZk...",
  "kzzzzzzk.kZkk...",
  ".kzzzzk..kZZZk..",
  "..kkkk...kkkkk..",
  "................",
  "................",
];

const BUG: ItemSprite = [
  "................",
  "..k..........k..",
  "...kk......kk...",
  "....kkkkkkkk....",
  "...kfgggggggk...",
  "..kfgkgggkggfk..",
  ".kfgggWgWgggfk..",
  "kfggggggggggfk..",
  "kfgkgggggkgggfk.",
  "kfgggggggggggfk.",
  ".kfgkgggkgggfk..",
  "..kfgggggggfk...",
  "...kkfgggfkk....",
  "...k..kkk..k....",
  "..k.........k...",
  "................",
];

const EMPTY_BATTERY: ItemSprite = [
  "................",
  ".....kkkkkk.....",
  "....kkZZZZkk....",
  "...kkkkkkkkkk...",
  "...kZjjjjjjZk...",
  "...kZjjjjjjZk...",
  "...kZjjjjjjZk...",
  "...kZjjRRjjZk...",
  "...kZjRRRRjZk...",
  "...kZjjRRjjZk...",
  "...kZjjjjjjZk...",
  "...kZjjjjjjZk...",
  "...kZjjjjjjZk...",
  "...kkkkkkkkkk...",
  "................",
  "................",
];

const TORNADO: ItemSprite = [
  "................",
  ".kkkkkkkkkkkkk..",
  "kZZZZZZZZZZZZZk.",
  ".kZZZZZZZZZZZk..",
  "..kkZZZZZZZkk...",
  "...kZZZZZZZk....",
  "....kkZZZkk.....",
  "....kZZZZZk.....",
  ".....kkZkk......",
  ".....kZZZk......",
  "......kZk.......",
  "......kZk.......",
  ".....kZk........",
  ".....kk.........",
  "....kk..........",
  "................",
];

const ROADBLOCK: ItemSprite = [
  "................",
  "................",
  "..kkkkkkkkkkkk..",
  "..kYYkkoookkYk..",
  "..kYYkkoookkYk..",
  "..kkooYYkkooYk..",
  "..kkooYYkkooYk..",
  "..kYYkkoookkYk..",
  "..kYYkkoookkYk..",
  "..kkkkkkkkkkkk..",
  "...kk......kk...",
  "...kk......kk...",
  "..kkkk....kkkk..",
  "................",
  "................",
  "................",
];

const WAVE: ItemSprite = [
  "................",
  "..........kkk...",
  ".......kkkBBBk..",
  ".....kkBBBBBBk..",
  "....kBBBiiBBBk..",
  "...kBBBiiiiBBk..",
  "...kBBiiiiiBBk..",
  "..kBBBiiiiBBBk..",
  "..kBBBBiiBBBBk..",
  "..kBBBBBBBBBBk..",
  ".kBBBBBBBBBBBk..",
  ".kBBBBBBBBBBBk..",
  ".kkkkkkkkkkkkk..",
  "................",
  "................",
  "................",
];

const SIREN: ItemSprite = [
  "................",
  ".......kk.......",
  "......kRRk......",
  "..k..kRRRRk..k..",
  "...kkRReeRRkk...",
  "....kReeeeRk....",
  "...kRReeeeRRk...",
  "..kRRReeeeRRRk..",
  "..kRRRRRRRRRRk..",
  "..kkkkkkkkkkkk..",
  "..kZZZZZZZZZZk..",
  "..kZZZZZZZZZZk..",
  "..kkkkkkkkkkkk..",
  "................",
  "................",
  "................",
];

const NOSIGNAL: ItemSprite = [
  "................",
  "..kkkkkkkkkk....",
  "..kzzzzzzzzk....",
  "..kzWWWWWWzk....",
  "..kzWjjjjWzk....",
  "..kzWjRRjWzk..k.",
  "..kzWjRRjWzk.kR.",
  "..kzWjjjjWzkkR..",
  "..kzWWWWWWzkR...",
  "..kzzzzzzzkRk...",
  "..kzzzzzzRzk....",
  "..kzzzzzRzzk....",
  "..kkkkkRkkkk....",
  ".....kRk........",
  "....kR..........",
  "................",
];

const BLOCKED: ItemSprite = [
  "................",
  "....kkkkkkk.....",
  "..kkRRRRRRRkk...",
  ".kRRRRRRRRRRRk..",
  ".kRRRkkkkRRRRk..",
  "kRRRkWWWWkRRRRk.",
  "kRRkWWWWkRRRRRk.",
  "kRRkWWWkRRRRRRk.",
  "kRRkWWkRRRRRRRk.",
  "kRRRkWkRRRRRRRk.",
  "kRRRRkkRRRRRRk..",
  ".kRRRRRRRRRRRk..",
  "..kkRRRRRRRkk...",
  "....kkkkkkk.....",
  "................",
  "................",
];

const FACTORY: ItemSprite = [
  "................",
  "..j...j...j.....",
  ".jjj.jjj.jjj....",
  "..j...j...j.....",
  "....kk..kk......",
  "....kk..kk......",
  "kkkkkkkkkkkkkk..",
  "kzzzkzzzkzzzzk..",
  "kzWzkzWzkzWWzk..",
  "kzzzkzzzkzzzzk..",
  "kzWzkzWzkzWWzk..",
  "kzzzkzzzkzzzzk..",
  "kkkkkkkkkkkkkk..",
  "................",
  "................",
  "................",
];

// =========================================================== POWERUPS ======

const PU_SHIELD_I: ItemSprite = [
  "................",
  "..kkkkkkkkkkkk..",
  ".kiiiiiiiiiiiik.",
  "kiicccccccccciik",
  "kicccccccccccik.",
  "kicccWWWWccccik.",
  "kicccWWWWccccik.",
  "kicccccccccccik.",
  ".kicccccccccik..",
  ".kicccccccccik..",
  "..kicccccccik...",
  "...kicccccik....",
  "....kicccik.....",
  ".....kiiik......",
  "......kkk.......",
  "................",
];

const PU_MULTI_I: ItemSprite = [
  "................",
  "....kkkkkkkk....",
  "..kkyyyyyyyykk..",
  ".kyyYYYYYYYYyyk.",
  "kyyYYkkYYkkYYyyk",
  "kyYYYkkYYkkYYYyk",
  "kyYYYYkkkkYYYYyk",
  "kyYYYYYkkYYYYYyk",
  "kyYYYYkkkkYYYYyk",
  "kyYYYkkYYkkYYYyk",
  "kyyYYkkYYkkYYyyk",
  ".kyyYYYYYYYYyyk.",
  "..kkyyyyyyyykk..",
  "....kkkkkkkk....",
  "................",
  "................",
];

const PU_MAGNET_I: ItemSprite = [
  "................",
  "..kkkk....kkkk..",
  ".kRRRRk..kRRRRk.",
  "kRRRRRRkkRRRRRRk",
  "kRRkkRRkkRRkkRRk",
  "kRRkkRRkkRRkkRRk",
  "kRRkkRRkkRRkkRRk",
  "kRRkkRRRRRRkkRRk",
  "kRRkkRRRRRRkkRRk",
  "kRRkkkkkkkkkkRRk",
  "kRRRRRRRRRRRRRRk",
  "kZZZRRRRRRRRZZZk",
  "kZZZkkkkkkkkZZZk",
  ".kkk........kkk.",
  "................",
  "................",
];

// ============================================================ REGISTRY =====

export const ITEMS: Record<string, ItemSprite> = {
  CLIPBOARD, DNA, PILL, BARCHART, MEDAL, HEART, PUZZLE, GEAR, BATTERY, ORB,
  BRAIN, DISH, PALETTE_ART, NOTE, CAMERA, WRENCH, SENSOR, CRATE, SPROUT, DROP,
  SATELLITE, MAP_ITEM, PIN, BOOKS, PENCIL, LEAF, SUN, WIND,
  VIRUS, BROKEN_LOCK, XMARK, BANDAGE, RAINCLOUD, DOWNCHART, EXPLOSION, TRUCK,
  FIRE, SNOWFLAKE, LIGHTNING, VOID_HOLE, WARNING, SLEEP, BUG, EMPTY_BATTERY,
  TORNADO, ROADBLOCK, WAVE, SIREN, NOSIGNAL, BLOCKED, FACTORY,
};

export const POWERUP_ITEMS: Record<string, ItemSprite> = {
  shield: PU_SHIELD_I,
  multiplier: PU_MULTI_I,
  magnet: PU_MAGNET_I,
  slowmo: PU_SHIELD_I,
  extraLife: PU_MAGNET_I,
};

/** Maps each sector's collectibles/obstacles (by defIndex order in
 *  sectors.json) onto a concrete item sprite, so every pickup reads as the
 *  thing its label actually names. */
export const SECTOR_ITEMS: Record<SectorId, { collect: string[]; obstacle: string[] }> = {
  healthcare: {
    collect: ["CLIPBOARD", "DNA", "PILL"],
    obstacle: ["VIRUS", "BROKEN_LOCK", "XMARK"],
  },
  sports: {
    collect: ["BARCHART", "MEDAL", "HEART"],
    obstacle: ["BANDAGE", "RAINCLOUD", "DOWNCHART"],
  },
  semiconductors: {
    collect: ["PUZZLE", "GEAR", "BATTERY"],
    obstacle: ["EXPLOSION", "TRUCK", "FIRE"],
  },
  quantum: {
    collect: ["ORB", "BRAIN", "DISH"],
    obstacle: ["SNOWFLAKE", "LIGHTNING", "VOID_HOLE"],
  },
  entertainment: {
    collect: ["PALETTE_ART", "NOTE", "CAMERA"],
    obstacle: ["WARNING", "SLEEP", "BUG"],
  },
  robotics: {
    collect: ["WRENCH", "SENSOR", "CRATE"],
    obstacle: ["LIGHTNING", "FIRE", "EMPTY_BATTERY"],
  },
  agriculture: {
    collect: ["SPROUT", "DROP", "SATELLITE"],
    obstacle: ["BUG", "FIRE", "TORNADO"],
  },
  mobility: {
    collect: ["MAP_ITEM", "BATTERY", "PIN"],
    obstacle: ["ROADBLOCK", "WAVE", "SIREN"],
  },
  education: {
    collect: ["BOOKS", "BRAIN", "PENCIL"],
    obstacle: ["NOSIGNAL", "DOWNCHART", "BLOCKED"],
  },
  climate: {
    collect: ["LEAF", "SUN", "WIND"],
    obstacle: ["WAVE", "FIRE", "FACTORY"],
  },
};
